export { default as Battelle } from './Battelle.png';
export { default as DynCorp } from './DynCorp.png';
export { default as Fluor } from './Fluor.png';
export { default as Hitachi } from './Hitachi.png';
export { default as NRECA } from './NRECA.jpg';
export { default as PointBlank } from './Point Blank.png';
export { default as SEC } from './SEC.png';
export { default as SOC } from './SOC.png';
export { default as TASC } from './TASC.png';
export { default as ArchitectOfTheCapitol } from './ArchitectOfTheCapitol.png';
